### ISSUE TITLE
I can't seem to perform basic mouse actions on the touchscreen outside of moving the cursor and left clicking.

### ISSUE THREAD

**Issue by Proaxel** [moonlight-stream/moonlight-ios#284]
If I do the gesture for right clicking (Hold one finger, tap a second) the cursor on the host jumps to a random place on the screen. If the window in focus has a scrollbar, then it jumps to a random place as well.

I can't get the click and drag to work either... if I do a tap, hold, and drag like the guide says, the cursor just moves as if I wasn't holding the button down at all. 

A normal Left Click works fine. 

Am I just not doing these simple gestures correctly, or is it something else?

**Comment by cgutman** [comment]
The right click gesture in the current release works best if you tap and release with both fingers. The gesture detection is also very sensitive to accidental movements during the "hold" phase of the drag which will invalidate the drag and turn it into a normal mouse move.

I fixed the right click gesture handling for the case you described in https://github.com/moonlight-stream/moonlight-ios/commit/45dbd46da1ec9b5b61956227630a02c607059e8a

I also implemented suppression of accidental movements for drag and right click in https://github.com/moonlight-stream/moonlight-ios/commit/7d7500b1876609d29c9e2caacb6a4116e9a6c00c

**Comment by Proaxel** [comment]
Okay, I hope those fixes work!

**Comment by cgutman** [comment]
Fix released in v1.4.0

**Comment by Proaxel** [comment]
@cgutman The right click works now! That alone makes it much better! However I still can't get the click and drag to work at all. I'm pretty sure I am holding my finger as still as it can get. 

When you select text or move the text input cursor in iOS, you do a similar gesture: You tap and hold in one place for a quarter of a second, then drag around. I can select text on my device just fine, yet I can't do a click and drag in Moonlight at all. Perhaps you should modify the gesture to behave more like iOS's?

**Comment by cgutman** [comment]
@Proaxel That's similar to how it works with Moonlight. If you tap and hold within a 20 pixel radius for 650 ms, it activates a drag. We can't be as liberal with activating a drag as a typical text selection gesture because it might erroneously begin dragging when someone is just trying to do some very fine mouse cursor movement.

What device is this that you're using?

**Comment by Proaxel** [comment]
@cgutman I am using an iPhone 6s Plus. Is Force Touch implementation possible at all? My second thought was perhaps use Force Touch as a second option when activating a click and drag.
