### ISSUE TITLE
New Magic Keyboard (M4) Trackpad Unresponsive

### ISSUE THREAD

**Issue by Nonary** [moonlight-stream/moonlight-ios#626]
**Describe the bug**
The latest M4 Magic Keyboard trackpad does not appear to function once a stream has started, it works fine prior to starting the stream. Other applications such as Remote Desktop do not appear to have the same issues, so I suspect it has to do with API calls of some kind on Moonlights side.

**Steps to reproduce**
Have an M4 IPad with the New Magic Keyboard

Start a stream, attempt to move the mouse

**Screenshots**
Not necessary, mouse just gets stuck.

**Affected games**
All games impacted.

**Other Moonlight clients**
- Does the issue occur when using Moonlight on PC or Android? No, this is an iOS exclusive issue.

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? No
- If so, which settings have been changed?
- Does the problem still occur after reverting settings back to default?

**Gamepad-related issues (please complete if problem is gamepad-related)**
- Do you have any gamepads connected to your host PC directly?
- If gamepad input is not working, does it work if you use Moonlight's on-screen controls?
- Does the problem still remain if you stream the desktop and use https://html5gamepad.com to test your gamepad?
  - Instructions for streaming the desktop can be found here: https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide

**Device details (please complete the following information)**
 - iOS/tvOS version: 17.5
 - Device model: iPad Pro 13-inch (M4)

**Server PC details (please complete the following information)**
 - OS: Windows 11 22H3

**Comment by myMartek** [comment]
Wanted to create this issue as well. I can confirm this issue on my side.  With the previous Magic Keyboard it is still working, only the new M4 variant is not. The keyboard itself is working by the way. So it’s just the touchpad.

**Comment by justinbadal** [comment]
Adding in my issue here. I am using Sunshine as the host. Tried a number of configuration combinations and couldn't get it to work.

**Comment by rpheuts** [comment]
Confirmed here as well. The keyboard part works, but not the trackpad. As others mentioned, this is still working on my older M2 iPad and Magic Keyboard, but doesn't work on the new hardware anymore.

**Comment by DANTIGO** [comment]
As of 05/16/24 this problem still exists. I Just got the new Magic Keyboard for my M4 13-Inch and I'm also having this issue. Everything else on the keyboard is fully functional besides the function keys only reacting for the iPadOS itself, but other than that things are great. I should add that the escape key is the only function key that actually works as intended for Moonlight. This is strictly exclusive to the new Magic Keyboard as my older iPad and Magic Keyboard are working just fine.

**Comment by blackgold9** [comment]
Same, m4 ipad pro and magic keyboard.

**Comment by alotofentropy** [comment]
Typing this from the M4 magic keyboard, but also unable to use the trackpad to control the mouse :(

**Comment by DANTIGO** [comment]
Is there any recommended route of action to contact apple and inform them with the appropriate information for them to diagnose and patch this issue? It can't be something that's intended if it works fine on their previous keyboard. All the did was add a few buttons and make the trackpad bigger.

**Comment by julianq** [comment]
Adding to the chorus here - M4 magic keyboard typing works, trackpad does not.

**Comment by myMartek** [comment]
Since iPadOS 17.5.1 was released today I gave it another try. Unfortunately the issue still is not fixed.

**Comment by moyer** [comment]
@myMartek Is the same issue occurring in other Remote Desktop applications? Like Jump or Windows RDP?

I also just submitted a Feedback to Apple. Hope they get this fixed 🤞

**Comment by rpheuts** [comment]
Not sure how helpful this is, but I did confirm it still works with the  AWS Workspaces client which has not seen an update for like a year. They must be using a different way to capture the pointer.

**Comment by myMartek** [comment]
I have not used AWS Workplace, but I guess this is the main difference: Most apps do not „Capture“ the pointer.
Mouse support was added in iPadOS 13.4 but did not have an API to capture the mouse. With capturing I refer to using the pointer exklusive for the opened app. So a captured mouse will not interact with the home indicator bar at the bottom or trigger any other things in the OS.

Starting with iPadOS 14 Apple added GCMouse APIs in order to fully capture the mouse. This is eg. needed for FPS games. This API seems to be broken for the current magic keyboard.

Best example for this is Steam Link. This app will allow the usage of the trackpad in Windows or Steam Big Picture mode, but when you open a FPS game Steam changes the input method to GCMouse to allow for real capturing and then the mouse does not work anymore as with moonlight in general. Steams philosophy is that when no FPS game is open it uses the „old“ APIs to not capture the mouse in order to allow easier interaction with iPadOS.

So currently the issue is only present when you want to use the mouse inputs exclusively.

**Comment by Ysabelle12** [comment]
Not working for me as well. works with external mouse but not the trackipad for m4

**Comment by Doeca** [comment]
maybe there will be big change after wwdc2024 so Apple changed the api for m4 ipad

**Comment by joetessy** [comment]
Still nothing? :(

**Comment by pilot-luch** [comment]
I would like to report my use case. Even without any media playing device keyboard will become unresponsive. No input detection from the trackpad or keyboard, even though it’s illuminated. The device seems to “respring” the last time this happened to correct itself.

**Comment by systox** [comment]
New iPad 13 Magic Keyboard touchpad doesn’t work with moonlight.  It can scroll and it can click. But it can’t move the mouse.

**Comment by Ysabelle12** [comment]
I’ve got some temporary fixes: enable AssistiveTouch in  accessibility. It works for me and it should in theory work for every M4 iPad user. However the downside of this is disable some input acceleration. You may or may not like that.

**Comment by joetessy** [comment]
Confirming @Ysabelle12’s workaround worked for me

**Comment by myMartek** [comment]
For me this makes no difference. Is there any specific option you enabled in the assistive touch section besides the main toggle?

**Comment by alotofentropy** [comment]
> I’ve got some temporary fixes: enable AssistiveTouch in accessibility. It works for me and it should in theory work for every M4 iPad users that use Magic Keyboard M4. However the downside of this is disable some input acceleration. You may or may not like that.

Yep, this works for me. I only just needed to enable it and it started working. I really do hate the acceleration curve it uses though. Not sure if its habitual or just err designed to be annoying.

**Comment by rpheuts** [comment]
> For me this makes no difference. Is there any specific option you enabled in the assistive touch section besides the main toggle?

It didn’t work for me initially, but after fiddling with it for a while (I believe adjusting the speed of the pointer finally fixed it) it did start working. I was able to adjust the speed to pretty much match my regular touchpad input. I also added a shortcut button to my home screen that toggle assistive touch on/off right next to the moonlight app. So I can leave it off for most of the time, but just quickly flick it on when I launch moonlight.

**Comment by moyer** [comment]
> I’ve got some temporary fixes: enable AssistiveTouch in accessibility. It works for me and it should in theory work for every M4 iPad users that use Magic Keyboard M4. However the downside of this is disable some input acceleration. You may or may not like that.

This worked for me. I'm assuming turning on AssistiveTouch switches the mouse API used, so it's no longer using GCMouse, which is where the bug is. Direct mouse capture is still something you want for gaming (and low input lag in general) so hopefully it still gets fixed.

**Comment by hxssgaa** [comment]
I turned on the AssistiveTorch but didn’t work for me for m4 iPad Pro. Hope it gets fixed soon as I really to use trackpad.

**Comment by alotofentropy** [comment]
Try play with the different settings in assistive touch. I think it will cause it to change ios back to a working API. I hope it does get fixed soon though. I dont like the mapping curves with assistive touch. MikeSent from my iPhoneOn 1 Jun 2024, at 12:30 AM, Huang Xin ***@***.***> wrote:﻿
I turned on the AssistiveTorch but didn’t work for me for m4 iPad Pro. Hope it gets fixed soon as I really to use trackpad.

**Comment by shortmemez** [comment]
Looks like Apple plans to fix this in a future OS update:

<img width="920" alt="image" src="https://github.com/moonlight-stream/moonlight-ios/assets/141759015/f6e1ef2c-fafd-47f4-beb3-0fcc9790aba4">

**Comment by Nonary** [comment]
Can confirm assistive touch workaround does work, but only after changing the sensitivity. You also need to make sure Moonlight is set to touchpad mode and not touch screen, otherwise the cursor resets every time you click

**Comment by myMartek** [comment]
Unfortunately iPadOS 18 Beta 1 does not fix the issue

**Comment by Leask** [comment]
same here

**Comment by itschendai** [comment]
same here

**Comment by theJayTea** [comment]
i have the same issue too! i hope apple fixes this, welp.

**Comment by n0brainer** [comment]
> Unfortunately iPadOS 18 Beta 1 does not fix the issue

Thanks, I haven’t been brave enough to install on my iPad.  Log feedback with Apple if you’re in the betas. The squeaky wheel gets the grease.

Also, be careful discussing non-public Beta information… prior experience has taught me that they are watching, no matter how obscure the references or post locations are.

**Comment by myMartek** [comment]
Has anyone tried 17.6 Beta yet?

**Comment by TheMaxXHD** [comment]
> Has anyone tried 17.6 Beta yet?

Probably doesn't work either based on the dev release notes for it. https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-17_6-release-notes

Also might not be a bad idea to post about the bug on the apple dev forums, maybe get some traction on it. Not seeing anything relating to it under the gamekit forum section.

**Comment by n0brainer** [comment]
I guess now that it’s public beta I can safely comment. I tried it and it did work for me.  It’s still beta so ymmv.

**Comment by khant14** [comment]
Did not work for me on 18 beta

**Comment by Leask** [comment]
I just upgraded, and it works! The only remaining issue is background streaming. 😄

**Comment by joetessy** [comment]
works for me!

**Comment by alotofentropy** [comment]
Agreed. Issue is fixed iOs 18 beta 2 👍

**Comment by Colindm8** [comment]
Any news if this is fixed in 17.6 beta 2? Hoping it’s fixed in that as I don’t want to put the 18 beta on my iPad.

**Comment by Doeca** [comment]
> Any news if this is fixed in 17.6 beta 2? Hoping it’s fixed in that as I don’t want to put the 18 beta on my iPad.

tested fixed in ipados 17.6 public beta(it seems to be developer beta 1)

**Comment by UltimateBrent** [comment]
I can't be sure of the cause, as I'm on the iOS 18 beta and I don't have another m4 ipad to test, but either iOS or Moonlight fixed this. It works now.

**Comment by Allen-GX** [comment]
This problem exists in VisionPro (because VisionOS uses ipadOS to be compatible with Moonlight APP), I still cannot use a Bluetooth mouse to operate the screen, only the scroll wheel is working.

**Comment by myMartek** [comment]
I'll be receiving my Vision Pro tomorrow and can test it then. However, Bluetooth mouse support is generally not available in visionOS 1; it was introduced in the beta versions of visionOS 2. I'll report back on whether it works with Moonlight on the new version of visionOS.

**Comment by benjaminrclayton** [comment]
Tested and verified fix is in 17.6 public release.

**Comment by Zwan-lab** [comment]
updated to iPadOS 18.0.1, trackpad now working!

**Comment by Cicton** [comment]
This issue happened to me as well on iPadOS 18.2 beta 2.   I discovered inside settings > accessibility > pointer control, that the option to IGNORE TRACKPAD was enabled.  Turned that off and issue fixed.  Hope this helps.

**Comment by hmottestad** [comment]
Trackpad on my Magic Keyboard with my M4 iPad Pro running 18.3 is working. Only issue I'm having is that my cursor keeps disappearing.

**Comment by instamat** [comment]
iPad Air 13 (M4) using a Magic Keyboard (for Air) and the onscreen cursor isn't aligned with the remote PC cursor. It works, but sometimes I have to move the PC cursor "over" to the virtual monitor area to use it again in Moonlight.
